import { Trek } from './types';

export const TREK_REGIONS = [
  'Himachal Pradesh',
  'Karnataka',
  'Maharashtra',
  'Northeast India',
  'Uttarakhand',
];

export const TREK_SEASONS = ['Spring', 'Summer', 'Monsoon', 'Autumn', 'Winter'];

export const TREK_DIFFICULTIES = ['Easy', 'Moderate', 'Challenging', 'Extreme'];

export const TREK_TERRAINS = ['Forest', 'Mountain', 'Valley', 'Alpine', 'Technical'];

// Sample Trek Data
export const SAMPLE_TREKS: Trek[] = [
  {
    id: 'kheerganga-trek',
    name: 'Kheerganga: The Sacred Highland',
    region: 'Himachal Pradesh',
    season: ['Spring', 'Summer', 'Autumn'],
    difficulty: 'Moderate',
    terrain: ['Forest', 'Mountain'],
    maxAltitude: 2680,
    duration: 3,
    groupSize: 12,
    groupSizeMin: 4,
    moodWord: 'Serene',
    narrative:
      'Walk through rhododendron forests into the mists of a sacred Himalayan spring. Kheerganga tells the story of spiritual seekers and shepherds, where hot springs meet eternal snow.',
    whyShouldNotDo: [
      'Fear of heights or exposure',
      'Recent joint injuries',
      'Extreme heat sensitivity',
      'Panic disorder in crowded spaces',
    ],
    routeStory: [
      {
        day: 1,
        title: 'Gateway to the Gods',
        narrative:
          'Drive through pine forests to Kasol. Trek begins on ancient shepherds trail. Overnight in village homestay.',
        altitude: 1700,
        distance: '6 km',
        highlights: ['Parvati River views', 'Traditional village', 'Local pottery'],
      },
      {
        day: 2,
        title: 'Ascent into Mist',
        narrative:
          'Climb through rhododendron thickets. Forest opens to alpine meadows. Hot springs await at camp.',
        altitude: 2680,
        distance: '8 km',
        highlights: ['Rhododendron forest', 'Hot springs', 'Alpine meadows', 'Sunset from ridge'],
        camp: 'Kheerganga Hot Springs',
      },
      {
        day: 3,
        title: 'Return & Reflection',
        narrative:
          'Morning soak in natural hot springs. Descend through forest to Kasol. Evening free for exploration.',
        altitude: 1700,
        distance: '6 km',
        highlights: ['Sunrise soak', 'Waterfall encounter', 'Village markets'],
      },
    ],
    lifeOnTrail: {
      stay: 'Mix of homestays and mountain camps with basic amenities. Communal sleeping arrangements.',
      food: 'Local Himachali cuisine. Vegetarian with options. Hot meals prepared fresh. Purified water provided.',
      weather:
        'Spring: 8-18°C, clear skies. Summer: 12-22°C, occasional rain. Autumn: 5-15°C, crisp mornings.',
      communication: 'Basic mobile connectivity. Satellite phone available with guides.',
      hygiene: 'Basic camp toilets. Water heated for washing. Hand sanitizers and wet wipes provided.',
      altitude_adjustment: 'Gradual ascent. One acclimatization day at camp. Guides monitor closely.',
    },
    safety: {
      guideRatio: '1 guide per 6 trekkers',
      protocols: ['Daily health check-ins', 'Emergency evacuation plan', 'First aid trained staff'],
      medical: 'First aid kit. Oxygen. Evacuation helicopter on standby. Guide with wilderness first aid certification.',
      insurance: 'Trek insurance mandatory. Coverage up to ₹5,00,000. Pre-existing conditions covered.',
      monitoring: 'Real-time GPS tracking. Daily check-in with base camp. Family contact protocol established.',
    },
    images: ['/trek-images/kheerganga-1.jpg', '/trek-images/kheerganga-2.jpg'],
    basePrice: 8999,
    inclusions: [
      'Professional guide',
      'All meals',
      'Camping equipment',
      'Trek permit',
      'Safety gear',
      'Transportation from Kasol',
    ],
    exclusions: ['Flight', 'Personal gear', 'Travel insurance', 'Activities outside trek'],
    batches: [
      {
        id: 'batch-kh-001',
        trekId: 'kheerganga-trek',
        startDate: '2026-03-15',
        endDate: '2026-03-17',
        availableSlots: 3,
        totalSlots: 12,
        pricePerPerson: 8999,
        leadGuide: 'Rajesh Kumar',
        coGuides: ['Priya Sharma'],
        status: 'closing-soon',
      },
      {
        id: 'batch-kh-002',
        trekId: 'kheerganga-trek',
        startDate: '2026-04-05',
        endDate: '2026-04-07',
        availableSlots: 8,
        totalSlots: 12,
        pricePerPerson: 9499,
        leadGuide: 'Vikram Singh',
        coGuides: ['Anjali Patel'],
        status: 'open',
      },
    ],
  },
  {
    id: 'brahmagiri-trek',
    name: 'Brahmagiri: The Elephant Trail',
    region: 'Karnataka',
    season: ['October', 'November', 'December', 'January'],
    difficulty: 'Easy',
    terrain: ['Forest', 'Valley'],
    maxAltitude: 1608,
    duration: 2,
    groupSize: 15,
    groupSizeMin: 5,
    moodWord: 'Gentle',
    narrative:
      'A sacred pilgrimage through Western Ghats forests, where wild elephants roam freely. Brahmagiri reveals the soul of South Indian wilderness.',
    whyShouldNotDo: [
      'Fear of wildlife',
      'Very young children',
      'Severe asthma',
      'Recent major surgery',
    ],
    routeStory: [
      {
        day: 1,
        title: 'Into the Ghats',
        narrative:
          'Drive to Brahmagiri base. Trek through coffee plantations and forest. Trail follows elephant routes.',
        altitude: 1200,
        distance: '5 km',
        highlights: ['Coffee plantations', 'Forest canopy', 'Bird watching', 'Local guide stories'],
      },
      {
        day: 2,
        title: 'Peak & Prayer',
        narrative:
          'Climb to Brahmagiri peak and temple. Panoramic views of Nilgiris. Descend same route.',
        altitude: 1608,
        distance: '6 km',
        highlights: ['Peak views', 'Ancient temple', 'Prayer ceremony', 'Nilgiri mountains'],
      },
    ],
    lifeOnTrail: {
      stay: 'Forest lodge or village homestay. Basic but clean. Shared rooms.',
      food: 'South Indian vegetarian cuisine. Rice-based meals. Fresh local vegetables. Coffee and tea abundant.',
      weather: 'Dry season. 12-22°C. Early morning mist. Clear afternoons.',
      communication: 'Mobile coverage in base area. Limited on trail.',
      hygiene: 'Clean toilets. Hot water available. Basic shower facilities.',
      altitude_adjustment: 'Minimal altitude gain. One day acclimatization.',
    },
    safety: {
      guideRatio: '1 guide per 8 trekkers',
      protocols: ['Wildlife awareness training', 'Group stick for noise'],
      medical: 'Basic first aid. Doctor nearby in village. Evacuation by jeep.',
      insurance: 'Trek insurance recommended.',
      monitoring: 'Guide checks group every hour. Daily communication with base.',
    },
    images: ['/trek-images/brahmagiri-1.jpg', '/trek-images/brahmagiri-2.jpg'],
    basePrice: 4999,
    inclusions: [
      'Professional guide',
      'All meals',
      'Accommodation',
      'Trek permit',
      'Transportation',
    ],
    exclusions: ['Flight', 'Personal gear', 'Activities outside trek'],
    batches: [
      {
        id: 'batch-br-001',
        trekId: 'brahmagiri-trek',
        startDate: '2026-10-10',
        endDate: '2026-10-11',
        availableSlots: 5,
        totalSlots: 15,
        pricePerPerson: 4999,
        leadGuide: 'Suresh Kumar',
        status: 'open',
      },
    ],
  },
  {
    id: 'markha-valley-trek',
    name: 'Markha Valley: High Altitude Adventure',
    region: 'Uttarakhand',
    season: ['Summer', 'Autumn'],
    difficulty: 'Extreme',
    terrain: ['Alpine', 'Mountain', 'Technical'],
    maxAltitude: 5000,
    duration: 7,
    groupSize: 8,
    groupSizeMin: 3,
    moodWord: 'Exhilarating',
    narrative:
      'Cross the roof of the world through alpine meadows and technical passes. Markha Valley offers solitude, silence, and profound mountain experience.',
    whyShouldNotDo: [
      'High altitude sickness history',
      'Heart conditions',
      'Severe anxiety',
      'Pregnancy',
      'Age over 60 without prior altitude experience',
    ],
    routeStory: [
      {
        day: 1,
        title: 'Acclimatization Day',
        narrative: 'Drive to Leh. Rest and acclimatization. Explore local markets.',
        altitude: 3500,
        distance: '0 km',
        highlights: ['Leh town', 'Shey Palace', 'Local markets'],
      },
      {
        day: 2,
        title: 'Trek Begins',
        narrative: 'Drive to Markha Valley entrance. First trek section. Moderate ascent.',
        altitude: 4200,
        distance: '12 km',
        highlights: ['Valley entrance', 'First camp', 'Sunset views'],
        camp: 'Markha Valley Base Camp',
      },
      {
        day: 3,
        title: 'High Alpine',
        narrative: 'Steep climb through alpine zone. Sparse vegetation. Technical scrambling.',
        altitude: 4600,
        distance: '10 km',
        highlights: ['Alpine flora', 'Technical terrain', 'Mountain panorama'],
        camp: 'High Camp 1',
      },
      {
        day: 4,
        title: 'Pass Crossing',
        narrative: 'Technical climb to main pass at 5000m. Thin air. Great achievement.',
        altitude: 5000,
        distance: '8 km',
        highlights: ['Pass summit', 'Prayer flags', 'Panoramic vistas'],
        camp: 'Pass Camp',
      },
      {
        day: 5,
        title: 'Descent & Traverse',
        narrative: 'Long descent to valley floor. Meadow traverse. Recovery day.',
        altitude: 4300,
        distance: '14 km',
        highlights: ['Meadow wildflowers', 'Stream crossing', 'Wildlife sightings'],
        camp: 'Meadow Camp',
      },
      {
        day: 6,
        title: 'Return Trek',
        narrative: 'Gradual descent. Final push. Approach exit point.',
        altitude: 3500,
        distance: '12 km',
        highlights: ['Forest re-entry', 'River descent'],
        camp: 'Final Camp',
      },
      {
        day: 7,
        title: 'Trek End & Recovery',
        narrative: 'Exit trek. Drive back to Leh. Rest day.',
        altitude: 3500,
        distance: '10 km',
        highlights: ['Trek completion', 'Celebration meal'],
      },
    ],
    lifeOnTrail: {
      stay: 'High altitude tents. Sleeping bags rated -20°C. Basic camp facilities.',
      food: 'High calorie meals. Pasta, rice, meat-based. Compressed air snacks. Hydration crucial.',
      weather:
        'Cold nights: -10 to 0°C. Warm days: 10-15°C. Sudden storms possible. UV exposure high.',
      communication: 'Satellite phone daily check-in. No mobile coverage.',
      hygiene: 'Wet wipes. Dry camping. Minimal water use. Sun protection essential.',
      altitude_adjustment: 'Acclimatization day in Leh. Slow ascent. Descent for recovery.',
    },
    safety: {
      guideRatio: '1 guide per 4 trekkers',
      protocols: [
        'Daily pulse oximeter readings',
        'Altitude awareness protocol',
        'Descent on first sign of sickness',
        'Emergency helicopter agreement',
      ],
      medical: 'Dexamethasone available. Oxygen bottles. Evacuation helicopter on call. Doctor briefing.',
      insurance: 'High altitude trek insurance mandatory. ₹10,00,000 minimum.',
      monitoring: 'Real-time satellite tracking. Hourly health check-ins. Family daily updates.',
    },
    images: ['/trek-images/markha-1.jpg', '/trek-images/markha-2.jpg'],
    basePrice: 24999,
    inclusions: [
      'Professional guide + porter',
      'All meals',
      'Camping equipment',
      'Oxygen on standby',
      'Satellite communication',
    ],
    exclusions: ['Flight to Leh', 'Personal gear', 'Insurance', 'Activities in Leh'],
    batches: [
      {
        id: 'batch-mk-001',
        trekId: 'markha-valley-trek',
        startDate: '2026-06-15',
        endDate: '2026-06-21',
        availableSlots: 0,
        totalSlots: 8,
        pricePerPerson: 24999,
        leadGuide: 'Sonam Dorje',
        coGuides: ['Tenzin Sherpa'],
        status: 'full',
      },
      {
        id: 'batch-mk-002',
        trekId: 'markha-valley-trek',
        startDate: '2026-08-05',
        endDate: '2026-08-11',
        availableSlots: 6,
        totalSlots: 8,
        pricePerPerson: 27999,
        leadGuide: 'Nawang Dorje',
        coGuides: ['Konchok Sherpa', 'Tenzin Dorje'],
        status: 'open',
      },
    ],
  },
];

export const GUIDES = [
  {
    id: 'guide-1',
    name: 'Rajesh Kumar',
    experience: 15,
    specialization: ['Himalayan Treks', 'Expedition', 'Photography'],
    bio: 'Ex-military mountaineer with 15 years of trekking experience across Indian Himalayas.',
    image: '/guides/rajesh.jpg',
    certifications: ['IFMGA', 'Wilderness First Responder', 'High Altitude Mountaineering'],
  },
  {
    id: 'guide-2',
    name: 'Priya Sharma',
    experience: 12,
    specialization: ['Cultural Treks', 'Women Leadership', 'Ecology'],
    bio: 'Environmental scientist turned guide. Passionate about sustainable tourism and local communities.',
    image: '/guides/priya.jpg',
    certifications: ['Wilderness First Aid', 'Environmental Science', 'Community Leadership'],
  },
  {
    id: 'guide-3',
    name: 'Sonam Dorje',
    experience: 20,
    specialization: ['Ladakh', 'High Altitude', 'Expedition'],
    bio: 'Born and raised in Ladakh. Expert on high altitude trekking and local culture.',
    image: '/guides/sonam.jpg',
    certifications: ['High Altitude Expert', 'Rescue Coordination', 'IFMGA'],
  },
];
